// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dijitalPano.Data;

#nullable disable

namespace dijitalPano.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("dijitalPano.Data.NobetciOgrenci", b =>
                {
                    b.Property<int>("NobetciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NobetTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OkulNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sinif")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .HasColumnType("TEXT");

                    b.HasKey("NobetciId");

                    b.ToTable("NobetciOgrenciler");
                });

            modelBuilder.Entity("dijitalPano.Data.NobetciOgretmen", b =>
                {
                    b.Property<int>("OgretmenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brans")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgretmenAd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OgretmenNobetTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgretmenSoyad")
                        .HasColumnType("TEXT");

                    b.HasKey("OgretmenId");

                    b.ToTable("NobetciOgretmenler");
                });

            modelBuilder.Entity("dijitalPano.Data.YemekTakip", b =>
                {
                    b.Property<int>("GunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Menu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("GunId");

                    b.ToTable("YemekTakibi");
                });
#pragma warning restore 612, 618
        }
    }
}
